### ISSUE TITLE
JAXB newer version issue

### ISSUE THREAD

**Issue by razvanTri** [Naros/debezium-quarkus-outbox#2]
I have a problem, and I'm not completely sure where it comes from. When I try to upgrade the version of this dependency `org.glassfish.jaxb:jaxb-runtime` from `2.3.9` to `3.0.0` I get this error: 

```
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.debezium.outbox.quarkus.deployment.OutboxProcessor#build threw an exception: java.lang.IllegalStateException: Failed to produce Outbox HBM mapping
```
...
```
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
   - with linked exception:
  [java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
```

Does Debezium not allow using a newer version for JAXB? What should I do to get it to work with the newer version? I use Debezium version 2.7.1.Final.

**Comment by Naros** [comment]
Hi @razvanTri, I believe for the Quarkus Outbox, we should be pulling in the JAXB version based on the Quarkus BOM most likely.  Last I checked, that should be 4.0.4 IIRC.  Is that not what you see?

**Comment by razvanTri** [comment]
@Naros thank you for your answer, the Quarkus BOM version I use is 2.16.12.Final. I believe the issue may be related to other older dependencies. I will wait for further updates to those dependencies before upgrading this one.

**Comment by Naros** [comment]
Well, Debezium has not used Quarkus 2.16 in quite some time now.  I believe we're using 3.12 or 3.13 atm.
